import type { CatalogItem } from './types';

/**
 * 100% 더미 데이터. 실제 상품 이미지 4장(옷1·2, 바지1·2)에 임의의 브랜드/가격/
 * 사이즈표를 붙였다 — 실존 상품 정보가 아니다.
 */
export const CATALOG: CatalogItem[] = [
  {
    id: 'top-1',
    category: 'top',
    subcategory: '반팔 티셔츠',
    brand: 'PLAIN DAYS',
    name: '헤비웨이트 반팔 티',
    price: 25000,
    colorName: '화이트',
    colorFamily: 'white',
    colorTone: 'neutral',
    fit: 'regular',
    styleTags: ['casual', 'minimal'],
    season: ['spring', 'summer'],
    sizeChart: {
      S: { 총장: 66, 어깨너비: 47, 가슴단면: 55 },
      M: { 총장: 68, 어깨너비: 49, 가슴단면: 57 },
      L: { 총장: 70, 어깨너비: 51, 가슴단면: 59 },
      XL: { 총장: 72, 어깨너비: 53, 가슴단면: 61 },
    },
    imagePath: '/catalog/tops/top-1.png',
    detail: '어느 하의와도 무난하게 어울리는 기본 반팔 티셔츠입니다.',
    material: '코튼 100%',
  },
  {
    id: 'top-2',
    category: 'top',
    subcategory: '셔츠',
    brand: 'ATELIER NOTE',
    name: '스탠다드 셔츠',
    price: 49000,
    colorName: '라이트 블루',
    colorFamily: 'blue',
    colorTone: 'cool',
    fit: 'slim',
    styleTags: ['classic', 'formal'],
    season: ['spring', 'fall'],
    sizeChart: {
      S: { 총장: 70, 어깨너비: 44, 가슴단면: 52, 소매길이: 61 },
      M: { 총장: 72, 어깨너비: 46, 가슴단면: 54, 소매길이: 63 },
      L: { 총장: 74, 어깨너비: 48, 가슴단면: 56, 소매길이: 65 },
    },
    imagePath: '/catalog/tops/top-2.png',
    detail: '깔끔한 슬림핏 셔츠. 캐주얼부터 세미 포멀까지 두루 어울립니다.',
    material: '코튼 100%',
  },
  {
    id: 'bottom-1',
    category: 'bottom',
    subcategory: '슬랙스',
    brand: 'PLAIN DAYS',
    name: '테이퍼드 슬랙스',
    price: 45000,
    colorName: '그레이',
    colorFamily: 'gray',
    colorTone: 'neutral',
    fit: 'slim',
    styleTags: ['minimal', 'formal'],
    season: ['spring', 'fall', 'winter'],
    sizeChart: {
      S: { 총장: 98, 허리단면: 36, 엉덩이단면: 48, 밑위: 26, 허벅지단면: 28, 밑단단면: 16 },
      M: { 총장: 100, 허리단면: 38, 엉덩이단면: 50, 밑위: 27, 허벅지단면: 29, 밑단단면: 17 },
      L: { 총장: 102, 허리단면: 40, 엉덩이단면: 52, 밑위: 28, 허벅지단면: 30, 밑단단면: 18 },
    },
    imagePath: '/catalog/bottoms/bottom-1.png',
    detail: '허리부터 발목까지 깔끔하게 떨어지는 테이퍼드 슬랙스.',
    material: '폴리에스터 65%, 레이온 33%, 스판덱스 2%',
  },
  {
    id: 'bottom-2',
    category: 'bottom',
    subcategory: '스트레이트 데님',
    brand: 'DENIM WORKS',
    name: '워시드 스트레이트 데님',
    price: 58000,
    colorName: '미드 블루',
    colorFamily: 'blue',
    colorTone: 'cool',
    fit: 'regular',
    styleTags: ['casual', 'amekaji'],
    season: ['spring', 'fall', 'winter'],
    sizeChart: {
      S: { 총장: 100, 허리단면: 38, 엉덩이단면: 50, 밑위: 27, 허벅지단면: 30, 밑단단면: 18 },
      M: { 총장: 102, 허리단면: 40, 엉덩이단면: 52, 밑위: 28, 허벅지단면: 31, 밑단단면: 19 },
      L: { 총장: 104, 허리단면: 42, 엉덩이단면: 54, 밑위: 29, 허벅지단면: 32, 밑단단면: 20 },
    },
    imagePath: '/catalog/bottoms/bottom-2.png',
    detail: '적당히 워시된 미드 블루 톤의 스트레이트 데님.',
    material: '코튼 98%, 폴리우레탄 2%',
  },
];
