import type { CatalogItem } from './types';

/**
 * 마일스톤 1 스텁 카탈로그 (6개). 전체 48개 카탈로그와 스타일 가중치(키 구간별
 * 참고 스타일 반영)는 마일스톤 2에서 확장한다.
 */
export const CATALOG: CatalogItem[] = [
  {
    id: 'top-001',
    category: 'top',
    subcategory: '옥스포드 셔츠',
    brand: 'ATELIER NOTE',
    name: '스탠다드 옥스포드 셔츠',
    price: 49000,
    colorName: '라이트 블루',
    colorFamily: 'blue',
    colorTone: 'cool',
    fit: 'regular',
    styleTags: ['minimal', 'classic'],
    season: ['spring', 'fall'],
    sizeChart: {
      S: { 총장: 70, 어깨너비: 44, 가슴단면: 52, 소매길이: 61 },
      M: { 총장: 72, 어깨너비: 46, 가슴단면: 54, 소매길이: 63 },
      L: { 총장: 74, 어깨너비: 48, 가슴단면: 56, 소매길이: 65 },
    },
    imagePath: '/catalog/tops/top-001.svg',
    detail: '어느 하의와도 무난하게 어울리는 라이트 블루 옥스포드 셔츠입니다. 세미 오버핏으로 편안하게 입을 수 있어요.',
    material: '코튼 100%',
  },
  {
    id: 'top-002',
    category: 'top',
    subcategory: '반팔 티셔츠',
    brand: 'PLAIN DAYS',
    name: '헤비웨이트 반팔 티',
    price: 25000,
    colorName: '차콜',
    colorFamily: 'black',
    colorTone: 'neutral',
    fit: 'relaxed',
    styleTags: ['casual', 'street'],
    season: ['summer'],
    sizeChart: {
      S: { 총장: 66, 어깨너비: 47, 가슴단면: 55 },
      M: { 총장: 68, 어깨너비: 49, 가슴단면: 57 },
      L: { 총장: 70, 어깨너비: 51, 가슴단면: 59 },
      XL: { 총장: 72, 어깨너비: 53, 가슴단면: 61 },
    },
    imagePath: '/catalog/tops/top-002.svg',
    detail: '도톰한 원단으로 핏이 무너지지 않는 릴렉스핏 반팔 티셔츠. 데님·슬랙스 어디에나 잘 어울립니다.',
    material: '코튼 100%',
  },
  {
    id: 'top-003',
    category: 'top',
    subcategory: '오버핏 니트',
    brand: 'ATELIER NOTE',
    name: '하프넥 니트',
    price: 59000,
    colorName: '아이보리',
    colorFamily: 'beige',
    colorTone: 'warm',
    fit: 'oversized',
    styleTags: ['minimal', 'casual'],
    season: ['fall', 'winter'],
    sizeChart: {
      M: { 총장: 68, 어깨너비: 52, 가슴단면: 58 },
      L: { 총장: 70, 어깨너비: 54, 가슴단면: 60 },
    },
    imagePath: '/catalog/tops/top-003.svg',
    detail: '부드러운 촉감의 하프넥 니트. 오버핏이라 이너로 셔츠를 레이어드해도 좋습니다.',
    material: '울 30%, 아크릴 70%',
  },
  {
    id: 'bottom-001',
    category: 'bottom',
    subcategory: '스트레이트 데님',
    brand: 'DENIM WORKS',
    name: '워시드 스트레이트 데님',
    price: 58000,
    colorName: '미드 블루',
    colorFamily: 'blue',
    colorTone: 'cool',
    fit: 'regular',
    styleTags: ['casual', 'amekaji'],
    season: ['spring', 'fall', 'winter'],
    sizeChart: {
      S: { 총장: 100, 허리단면: 38, 엉덩이단면: 50, 밑위: 27, 허벅지단면: 30, 밑단단면: 18 },
      M: { 총장: 102, 허리단면: 40, 엉덩이단면: 52, 밑위: 28, 허벅지단면: 31, 밑단단면: 19 },
      L: { 총장: 104, 허리단면: 42, 엉덩이단면: 54, 밑위: 29, 허벅지단면: 32, 밑단단면: 20 },
    },
    imagePath: '/catalog/bottoms/bottom-001.svg',
    detail: '적당히 워시된 미드 블루 톤의 스트레이트 데님. 캐주얼 룩의 기본이 되는 아이템입니다.',
    material: '코튼 98%, 폴리우레탄 2%',
  },
  {
    id: 'bottom-002',
    category: 'bottom',
    subcategory: '슬랙스',
    brand: 'PLAIN DAYS',
    name: '테이퍼드 슬랙스',
    price: 45000,
    colorName: '그레이',
    colorFamily: 'gray',
    colorTone: 'neutral',
    fit: 'slim',
    styleTags: ['minimal', 'formal'],
    season: ['spring', 'fall', 'winter'],
    sizeChart: {
      S: { 총장: 98, 허리단면: 36, 엉덩이단면: 48, 밑위: 26, 허벅지단면: 28, 밑단단면: 16 },
      M: { 총장: 100, 허리단면: 38, 엉덩이단면: 50, 밑위: 27, 허벅지단면: 29, 밑단단면: 17 },
      L: { 총장: 102, 허리단면: 40, 엉덩이단면: 52, 밑위: 28, 허벅지단면: 30, 밑단단면: 18 },
    },
    imagePath: '/catalog/bottoms/bottom-002.svg',
    detail: '허리부터 발목까지 깔끔하게 떨어지는 테이퍼드 슬랙스. 셔츠와 매치하면 단정한 캐주얼 룩이 완성됩니다.',
    material: '폴리에스터 65%, 레이온 33%, 스판덱스 2%',
  },
  {
    id: 'bottom-003',
    category: 'bottom',
    subcategory: '카고 팬츠',
    brand: 'DENIM WORKS',
    name: '와이드 카고 팬츠',
    price: 52000,
    colorName: '카키',
    colorFamily: 'khaki',
    colorTone: 'warm',
    fit: 'relaxed',
    styleTags: ['street', 'workwear'],
    season: ['spring', 'fall'],
    sizeChart: {
      M: { 총장: 103, 허리단면: 40, 엉덩이단면: 54, 밑위: 29, 허벅지단면: 33, 밑단단면: 22 },
      L: { 총장: 105, 허리단면: 42, 엉덩이단면: 56, 밑위: 30, 허벅지단면: 34, 밑단단면: 23 },
      XL: { 총장: 107, 허리단면: 44, 엉덩이단면: 58, 밑위: 31, 허벅지단면: 35, 밑단단면: 24 },
    },
    imagePath: '/catalog/bottoms/bottom-003.svg',
    detail: '넉넉한 실루엣의 카고 팬츠. 포켓 디테일로 스트릿 무드를 더했습니다.',
    material: '코튼 100%',
  },
];
